# Generated by Django 4.2.29 on 2026-03-18 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AddField(
            model_name='translation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='translation',
            name='source_language',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='translation',
            name='target_language',
            field=models.CharField(max_length=20),
        ),
    ]
